"""add apartment photos table

Revision ID: b450bd10cc98
Revises: d7674ea716f0
Create Date: 2026-05-22 18:29:33.325060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b450bd10cc98'
down_revision: Union[str, Sequence[str], None] = 'd7674ea716f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment_photos',
    sa.Column('apartment_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apartment_photos_apartment_id'), 'apartment_photos', ['apartment_id'], unique=False)
    op.drop_column('apartments', 'photos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('photos', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_apartment_photos_apartment_id'), table_name='apartment_photos')
    op.drop_table('apartment_photos')
    # ### end Alembic commands ###
