"""add photos table with binary data

Revision ID: e2d5e8402730
Revises: b450bd10cc98
Create Date: 2026-05-22 18:39:19.517892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2d5e8402730'
down_revision: Union[str, Sequence[str], None] = 'b450bd10cc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment_photos', sa.Column('data', sa.LargeBinary(), nullable=False))
    op.drop_column('apartment_photos', 'file_size')
    op.drop_column('apartment_photos', 'file_path')
    op.drop_column('apartment_photos', 'file_name')
    op.drop_column('apartment_photos', 'display_order')
    op.drop_column('apartment_photos', 'updated_at')
    op.drop_column('apartment_photos', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment_photos', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('apartment_photos', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('apartment_photos', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('apartment_photos', sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('apartment_photos', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('apartment_photos', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('apartment_photos', 'data')
    # ### end Alembic commands ###
